version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: myuser
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./internal/infra/database/migrations:/docker-entrypoint-initdb.d
    depends_on:
      - rabbitmq
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 3s
      retries: 5      
    networks:
      - mysqldb

  migrate:
    image: migrate/migrate
    networks:
      - default
      - mysqldb
    volumes:
      - ./internal/infra/database/migrations:/migrations
    command: "-path=/migrations -database 'mysql://root:root@tcp(mysql:3306)/orders' up"
    depends_on:
      mysql:
        condition: service_healthy
networks:
  mysqldb:      